# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- script: |
    cp ./index.js ./dist/Que-Me-Pongo/index.js
    cp ./server.package.json ./dist/Que-Me-Pongo/package.json
  displayName: 'copy index.js to artifact directory'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './dist/Que-Me-Pongo' 
    includeRootFolder: false 
    archiveType: 'zip'
    tarCompression: 'gz'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    replaceExistingArchive: true
  displayName: 'Creating zip file'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

